config/routes.rb
Omni::Application.routes.draw do

  root 'services#index'
  get 'services/:id',       to: 'services#show', as: 'service'
  resources :professionals, only: [:index, :show]
  resources :users,         only: [:index, :show, :edit, :update ]
  post 'actions',           to: 'actions#toggle_save', as: 'actions'

  post 'purchases',         to: 'purchases#create', as: 'purchases'

end

app/models/action.rb
class Action < ActiveRecord::Base

  belongs_to  :actionable,
              polymorphic: :true

  belongs_to  :user

  validates   :type, presence: true
  validates   :actionable_id, presence: true
  validates   :actionable_type, presence: true

  validates   :user_id,
              presence: true,
              :uniqueness => { scope: [:actionable_id, :actionable_type, :type] }

end

app/models/concerns/pictureable.rb
module Pictureable
  
  extend ActiveSupport::Concern

  included do

    has_many :pictureable_pictures,         as: :pictureable,
                                            dependent: :destroy

    has_many :pictures,                     through: :pictureable_pictures

  end

end

app/models/follow.rb
class Follow < Action 


end

app/models/picture.rb
class Picture < ActiveRecord::Base

  validates   :storage_key,
              presence: true,
              uniqueness: true

end

app/models/pictureable_picture.rb
class PictureablePicture < ActiveRecord::Base

  belongs_to  :picture

  belongs_to  :picturable,
              polymorphic: :true

end

app/models/professional.rb
class Professional < ActiveRecord::Base
  
  include Pictureable

  validates   :username,
              presence: true,
              uniqueness: true,  
              format: { with: /\A[a-zA-Z0-9][a-zA-Z0-9_]*\z/ }
  validates   :first_name,
              allow_blank: true,
              format: { with: /\A[a-zA-Z][a-zA-Z0-9\-\s']+\z/ }
  validates   :last_name,
              allow_blank: true,
              format: { with: /\A[a-zA-Z][a-zA-Z0-9\-\s']+\z/ }

  has_many :services
  belongs_to :picture

  def name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/save.rb
class Save < Action 


end

app/models/service.rb
class Service < ActiveRecord::Base
  
  include Pictureable
  
  validates :name, presence: true
  
  belongs_to :professional
  belongs_to :picture
end

app/models/user.rb
class User < ActiveRecord::Base
  
  include Pictureable

  validates   :username,
              presence: true,
              uniqueness: true, 
              format: { with: /\A[a-zA-Z0-9][a-zA-Z0-9_]*\z/ }
  validates   :first_name,
              allow_blank: true,
              format: { with: /\A[a-zA-Z][a-zA-Z0-9\-\s']+\z/ }
  validates   :last_name,
              allow_blank: true,
              format: { with: /\A[a-zA-Z][a-zA-Z0-9\-\s']+\z/ }

  belongs_to :picture
  has_many   :actions
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController

  def toggle_save
    result = "saved"
    if action = Action.find_by( action_params.merge( user_id: @current_user.id ) )
      action.destroy
      result = "save"
    else
      action = Action.create( action_params.merge( user_id: @current_user.id ) )
    end
    render json: "#{result}", status: 200
  end

  def action_params
    params.permit( :type, :actionable_id, :actionable_type )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :get_current_user

  def get_current_user
    @current_user = User.first
  end
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController

  def index
    @professionals = Professional.all
  end

  def show
    @professional = Professional.find( params[:id] )
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  before_action :purchaseable, only: [:create]

  def create
    # Set your secret key: remember to change this to your live secret key in production
    # See your keys here https://dashboard.stripe.com/account/apikeys
    Stripe.api_key = "sk_test_Cl3dcM7P0MHIsOckJJhXONkY"

    # Get the credit card details submitted by the form
    token = params[:stripeToken]
    amount = params[:amount]
    # Create the charge on Stripe's servers - this will charge the user's card
    begin
      charge = Stripe::Charge.create(
        :amount => amount, # amount in cents, again
        :currency => "usd",
        :source => token,
        :description => "Purchase of #{purchaseable.name} from Omni",
        :metadata =>  {
                        "purchaseable_type" => purchaseable.class.name,
                        "purchaseable_id" => purchaseable.id,
                      }
      )
    rescue Stripe::CardError => e
      # The card has been declined
    end

    #create purchase
    render json: "Charge successful!"

  end
end


def purchaseable
  purchaseable_class = params[:purchaseable_type].constantize
  @purchaseable ||= purchaseable_class.find( params[:purchaseable_id] )
end
# purchase
# amount
# user_id
# purchaseable_id
# purchaseable_type

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @services = Service.all
  end

  def show
    @service = Service.find( params[:id] )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_s3_direct_post, only: [ :edit, :update ]
  before_action :get_user, only: [ :show, :edit, :update ]
  
  def show

  end

  def edit

  end

  def update
    user_attributes = {}
    picture_attributes = user_params.delete( :picture_url )
    if picture_attributes.present?

      #TODO get more info for picture
      picture = Picture.create(
        storage_key: picture_attributes
      ) 

      user_attributes[:picture_id] = picture.id
    end
    @user.update( user_attributes )
    redirect_to @user
  end

  private
  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(
      key: "#{SecureRandom.uuid}-${filename}",
      success_action_status: '201', acl: 'public-read'
    )
  end
  def get_user
    @user = User.find( params[:id] )
  end

  def user_params
    params.require( :user ).permit( :picture_url )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omni</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header-cont">
  <div class = "header"> 

      <%= link_to image_tag("logo.png", :class => "smallLogo"), root_path  %>
      <% if @current_user.present? %>
          <%= link_to image_tag( 
            @current_user.picture.storage_key, :class => "userAvatar" ),
            @current_user %>
      <% end %>
  </div>
</div>

<%= yield %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/professionals/index.html.erb
<h1>Professionals</h1>
<% @professionals.each do |professional| %>
  --------------------------------------<br>
  username: <%= professional.username %><br>
  first_name: <%= professional.first_name %>
  <br><b>services:</b> <% professional.services.each do |service| %>
    <li>service name: <%= service.name %> </li>
  <%end%>
  <br>
<%end%>

app/views/professionals/show.html.erb
<%= stylesheet_link_tag "application.css" %>
<%= javascript_include_tag "application" %>


<!-- Prof Info -->

<div class= "col-md-4 mainProf">
  <p class="headerText"><%= @professional.location %> </br></br>
  <%= @professional.description %> </p>
</div>

<div class= "col-md-4 mainProf">
  <%= image_tag @professional.picture.storage_key, :id => "userAvatarBig" %>
  <p id="username"><%=@professional.first_name%> <%=@professional.last_name%></p>
  <p class="userIdentifier">@<%=@professional.username%></p>
</div>

  <div class= "col-md-4 mainProf">
    <p class="headerText followingNumber"><%= Action.where( 
        actionable_type: 'Professional',
        actionable_id: @professional.id 
      ).count %> <br><br></p>
      <div class="followingText">Followers</div>
      <%=button_to "#{@current_user.actions.where(
                      actionable_type: 'Professional', actionable_id: @professional.id
          ).present? ? "followed" : "follow"  }", "",
 class: "btn btn-primary #{@current_user.actions.where(
                      actionable_type: 'Professional', actionable_id: @professional.id
          ).present? ? "followed" : "follow"  }", id: "Professional-#{@professional.id}",
          action: "create" %><br><br>
  </div>



<!-- Grid...make infinite after user prof implemented if you have-->

<div class="wrap full">

    <% @professional.services.each do |service| %>
    <div class="box">
      <div class="boxInner">
        <%= image_tag ( 
          service.picture ? service.picture.storage_key : "tumblr_nf0pdmqriX1rwb4yto1_500.jpg" 
        ), :class => "boxInner" %>
          <div id="overlay">
            <div id="textdiv"><p> <%=service.name%> </p><hr><p> $<%= service.cost.round(2) %> </p></div>
            <div class="purchaseable"><%= render partial: "purchases/new",  locals: {purchaseable: service } %></div>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/purchases/_new.html.erb
<%= form_tag purchases_path do %>
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_uSaMNMcoEa39gLEs7Exnkbe4"
    data-image="/assets/logo.png"
    data-name="Omni"
    data-description="<%= purchaseable.description %>"
    data-amount=<%= (purchaseable.cost*100).to_i %>
    data-locale="en"
    data-currency="USD">
  </script>
  <%= hidden_field_tag :purchaseable_id, purchaseable.id %>
  <%= hidden_field_tag :purchaseable_type, purchaseable.class.name %>
<%= hidden_field_tag :amount, (purchaseable.cost*100).to_i %>
<% end %>

app/views/purchases/index.html.erb
Hi

app/views/services/index.html.erb
<%= stylesheet_link_tag "application.css" %>
<%= javascript_include_tag "application" %>

<body class="no-touch"> 


<!-- Carousel 

<div id="main">
  
  <ul class="slider">
    <li>
      <img src="http://lorempixel.com/output/abstract-q-c-1056-480-1.jpg" />
    </li>
    <li>
      <img src="http://lorempixel.com/output/abstract-q-c-1056-480-8.jpg" />
    </li>
    <li>
      <img src="http://lorempixel.com/output/abstract-q-c-1056-480-7.jpg" />
    </li>
    <li>
      <img src="http://lorempixel.com/output/abstract-q-c-1056-480-6.jpg" />
    </li>
  </ul>

</div>

-->

<!-- TEMP CAROUSEL HOLDER -->
<div id="main">
       <center> <%= image_tag ("http://lorempixel.com/output/abstract-q-c-640-480-1.jpg"), :class => "slider" %></center>
</div>



<!-- Grid...make infinite after user prof implemented -->

<div class="wrap">
    
    <!-- Define all of the tiles: -->
  <% @services.each do |service| %>
    <div class="box">
      <div class="boxInner" >
        <%= image_tag ( 
          service.picture ? service.picture.storage_key : "tumblr_nf0pdmqriX1rwb4yto1_500.jpg" 
        ), :class => "boxInner" %>
          <div id="overlay">

            <div id="textdiv"><p> <%=service.name%> </p><hr><p> $<%= service.cost.round(2) %> </p>
            </div>




          </div>
      </div>
    </div>
    <% end %>
<!--     <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">

        </div>
      </div>
    </div>
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">

        </div>
      </div>
    </div>
     <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">

        </div>
      </div>
    </div>   
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">

        </div>
      </div>
    </div>
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">

        </div>
      </div>
    </div>
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">
        </div>
      </div>
    </div>
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">
        </div>
      </div>
    </div>
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">
        </div>
      </div>
    </div>             -->
</div>

app/views/services/show.html.erb
<br><br><br><br>

<h2><%= @service.name %></h2>
<%= image_tag( @service.picture.storage_key, width: "150" ) if @service.picture.present? %><br>
<%= link_to @service.professional do %>
  by: <%= @service.professional.username %>
<% end %>

<%=link_to "<3", "",
 class: "#{@current_user.actions.where(
                      actionable_type: 'Service', actionable_id: @service.id
          ).present? ? "saved" : "save"  }", id: "Service-#{@service.id}", action: "create" %>



<%= render partial: "purchases/new",  locals: {purchaseable: @service } %>

app/views/users/edit.html.erb
<%= form_for(
  @user, html: {  class: 'directUpload', data: 
    { 
      'form-data' => (@s3_direct_post.fields),
      'url' => @s3_direct_post.url,
      'host' => URI.parse(@s3_direct_post.url).host 
    }
 }) do |f| %>

  <div class="field">
    <%= f.label :picture_url %>
    <%= f.file_field :picture_url %><br><br>
    <%= f.submit "Update" %>
  </div>

<% end %>

app/views/users/index.html.erb
<%= stylesheet_link_tag "application.css" %>
<%= javascript_include_tag "application" %>


<!-- Prof Info -->

<div class= "col-md-4 mainProf">
  <p class="headerText"><%= @current_user.location %> </br></br>
  <%= @current_user.description %> </p>
</div>

<div class= "col-md-4 mainProf">
  <!--need to change this to backend after I reupload the imagine without the carat -->
  <%= image_tag @current_user.picture.storage_key, :id => "userAvatarBig" %>
  <p id="username"><%=@current_user.first_name%> <%=@current_user.last_name%></p>
  <p class="userIdentifier">@<%=@current_user.username%></p>
</div>

  <div class= "col-md-4 mainProf">
    <p class="headerText followingNumber"><%= @current_user.actions.count %> <br><br></p>
      <div class="followingText">Following</div>

  </div>



<!-- Grid...make infinite after user prof implemented if you have-->

<div class="wrap full">
    
    <!-- Define all of the tiles: -->

    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">
            <div id="textdiv"><p> Look Name </p><hr><p> $75 </p></div>
        </div>
      </div>
    </div>
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">

        </div>
      </div>
    </div>
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">

        </div>
      </div>
    </div>
     <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">

        </div>
      </div>
    </div>   
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">

        </div>
      </div>
    </div>
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">

        </div>
      </div>
    </div>
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">
        </div>
      </div>
    </div>
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">
        </div>
      </div>
    </div>
    <div class="box">
      <div class="boxInner">
        <%= image_tag "tumblr_nf0pdmqriX1rwb4yto1_500.jpg", :class => "boxInner" %>
          <div id="overlay">
        </div>
      </div>
    </div>            
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "application.css" %>
<%= javascript_include_tag "application" %>


<!-- Prof Info -->

<div class= "col-md-4 mainProf">
  <p class="headerText"><%= @current_user.location %> </br></br>
  <%= @current_user.description %> </p>
</div>

<div class= "col-md-4 mainProf">
  <%= image_tag @current_user.picture.storage_key, :id => "userAvatarBig" %>
  <p id="username"><%=@current_user.first_name%> <%=@current_user.last_name%></p>
  <p class="userIdentifier">@<%=@current_user.username%></p>
</div>

  <div class= "col-md-4 mainProf">
    <p class="headerText followingNumber"><%= @current_user.actions.count %> <br><br></p>
      <div class="followingText">Following</div>

  </div>



<!-- Grid...make infinite after user prof implemented if you have-->

<div class="wrap full">
    
    <!-- Define all of the tiles: -->
  <% @current_user.actions.each do |action| %>
    <div class="box">
      <div class="boxInner" >
        <%= image_tag ( 
          action.actionable.picture ? action.actionable.picture.storage_key : "tumblr_nf0pdmqriX1rwb4yto1_500.jpg" 
        ), :class => "boxInner" %>
        <div id="overlay">
          <div id="textdiv"><p>  <%=action.actionable.name %> </p><hr>
            <p> <%= action.actionable.cost.round(2) if action.actionable.respond_to?(:cost)%> </p>
          </div>
          <% if action.actionable.respond_to?(:cost) %>
          <div class="purchaseable"><%= render partial: "purchases/new",  locals: {purchaseable: action.actionable } %></div>
          <% end %>
        </div>
      </div>
    </div>
  <%end%>

</div>